# a_tensor_initialization.py

In [1]:
import torch

In [2]:
t1 = torch.Tensor([1, 2, 3], device = 'cpu') # large 'T'ensor -> class
print(t1.dtype) # Make tensor based on [1, 2, 3], so that type of list is chagned
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
# t1_cuda = t1.to(torch.device('cuda'))
t1_cpu = t1.cpu()
print()

In [4]:
t2 = torch.tensor([1, 2, 3], device = 'cpu') # Small 't'ensor -> function
print(t2.dtype) # Make tensor using [1, 2, 3], so that type of list is not changed
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [5]:
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

# b_tensor_initialization.py

In [6]:
import torch
import numpy as np

In [7]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.Tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)
# Translate list to tensor by itself, so the type of the 1, 2, 3 is not changed (int64)
# Howeveer, l1, l2 's type were changed into float32

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1, 2, 3])
####################################################################################################


In [8]:
# np.array is not a list. Just like other language's array

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4) # Tensor is a class so the type is chagned into float32

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5) # tensor is a function so the type is not changed. int64

# Tensor and tensor always copy the given list(data)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6) # as_tensor does not copying the given list

# If you want to avoid copying the data, use np.array() with as_tensor()

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)


tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


# c_tensor_initialization_constant_values.py

In [9]:
import torch

In [10]:
t1 = torch.ones(size = (5, )) # size must be tuple, not number
t1_like = torch.ones_like(input = t1) # create new tensor as same size with t1 filled with 1

print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [11]:
t2 = torch.zeros(size = (6, ))
t2_like = torch.zeros_like(input = t2)

print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [12]:
t3 = torch.empty(size = (4, )) # fill with uninitialized data -> not zero
t3_like = torch.empty_like(input = t3)

print(t3)
print(t3_like)

tensor([1.0078e+00, 0.0000e+00, 3.3631e-44, 0.0000e+00])
tensor([9.1477e-41, 0.0000e+00, 5.6052e-45, 0.0000e+00])


In [13]:
t4 = torch.eye(n = 3) # create a n by n unit matrix which means 단위행렬

print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values.py

In [14]:
import torch

In [15]:
t1 = torch.randint(low = 10, high = 20, size = (1, 2)) # random integer between low and high
print(t1)

tensor([[13, 12]])


In [16]:
t2 = torch.rand(size = (1, 3)) # random float between 0 and 1 from a uniform distribution, which means 균등분포
print(t2)

tensor([[0.7141, 0.1482, 0.5107]])


In [17]:
t3 = torch.randn(size = (1, 3)) # random float between 0 and 1 from a standard normal distribution, which means 표준정규분포
print(t3)

tensor([[-1.2316,  0.1218,  0.6070]])


In [18]:
t4 = torch.normal(mean = 10.0, std = 1.0, size = (3, 2)) # random float from a normal distribution which mean and standard deviation are given, which means 평균과 편차가 주어진 정규분포
print(t4)

tensor([[ 8.7904, 10.1796],
        [11.0333,  9.2392],
        [ 9.1931, 11.7051]])


In [19]:
t5 = torch.linspace(start = 0.0, end = 5.0, steps =3) # Arithmetic progression, which means 등차수열
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [20]:
print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])



In [21]:
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

# with same seed, the values of random are always same

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion.py

In [22]:
import torch

In [23]:
a = torch.ones((2, 3)) # tensor's basic data type is float32
print(a.dtype)

b = torch.ones((2, 3), dtype = torch.int16) # set data type explicitly
print(b)

c = torch.rand((2, 3), dtype = torch.float64) * 20.
print(c)

d = b.to(torch.int32) # type conversion
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [24]:
double_d = torch.ones(10, 2, dtype = torch.double)
short_e = torch.tensor([[1, 2]], dtype = torch.short)

In [25]:
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

In [26]:
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

# Everything is same type

In [27]:
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [28]:
double_f = torch.rand(5, dtype = torch.double)
short_g = double_f.to(torch.short)

print((double_f * short_g).dtype) # if large type calculate with smaller type, it becomes large type

torch.float64


# f_tensor_operations.py

In [29]:
import torch

In [30]:
t1 = torch.ones(size = (2, 3))
t2 = torch.ones(size = (2, 3))

In [31]:
t3 = torch.add(t1, t2)
t4 = t1 + t2

print(t3)
print(t4)

print("#" * 30)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################


In [32]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2

print(t5)
print(t6)

print("#" * 30)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################


In [33]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2

print(t7)
print(t8)

print("#" * 30)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################


In [34]:
t9 = torch.div(t1, t2)
t10 = t1 / t2

print(t9)
print(t10)

# all the operations work same

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm.py

In [35]:
import torch

In [36]:
t1 = torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))
# return dot product, which means 내적.
# return data type is tensor. not number. so the size fo the tensor is empty []
# and the value of tensor is result of dot product

print(t1, t1.size())

tensor(7) torch.Size([])


In [37]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # matrix multiplication

print(t4, t4.size())

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


In [38]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # batch matrix multiplication

print(t7.size())

torch.Size([10, 3, 5])


# h_tensor_operations_matmul.py

In [39]:
import torch

In [40]:
t1 = torch.randn(3)
t2 = torch.randn(3)

print(torch.matmul(t1, t2).size()) # maumultiplication return dot product

torch.Size([])


In [41]:
t3 = torch.randn(3, 4)
t4 = torch.randn(4)

print(torch.matmul(t3, t4).size()) # same as upside shell

torch.Size([3])


In [42]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)

print(torch.matmul(t5, t6).size())

torch.Size([10, 3])


In [43]:
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)

print(torch.matmul(t7, t8).size())

torch.Size([10, 3, 5])


In [44]:
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)

print(torch.matmul(t9, t10).size())

torch.Size([10, 3, 5])


# i_tensor_broadcasting.py

In [45]:
import torch

In [46]:
t1 = torch.tensor([1., 2., 3.])
t2 = 2.

print(t1 * t2)

print("#" * 50, 1)

tensor([2., 4., 6.])
################################################## 1


In [47]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5]) # t4 caculate with each t3 elements

print(t3 - t4)

print("#" * 50, 2)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2


In [48]:
t5 = torch.tensor([[1., 2.], [3., 4.]])

print(t5 + 2.)
print(t5 - 2.)
print(t5 * 2.)
print(t5 / 2.)

print("#" * 50, 3)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3


In [49]:
def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)

print(normalize(t6).size())

print("#" * 50, 4)

torch.Size([3, 28, 28])
################################################## 4


In [50]:
t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])

print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

print("#" * 50, 5)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5


In [51]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

print("#" * 50, 6)

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6


In [52]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())

# error : 2 & 3 is not a multiple number for each other
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())

print("#" * 50, 7)

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7


In [53]:
t27 = torch.ones(4) * 5    # tensor([5., 5., 5., 5.])
print(t27)

t28 = torch.pow(t27, 2)    # tensor([25., 25., 25., 25.])
print(t28)

exp = torch.arange(1., 5.) # tensor([1., 2., 3., 4.])
a = torch.arange(1., 5.)   # tensor([1., 2., 3., 4.])
t29 = torch.pow(a, exp)
print(t29)

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing.py

In [54]:
import torch

In [55]:
x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

In [56]:
print(x[1])
print(x[:, 1])
print(x[1, 2])
print(x[:, -1]) # index can be minus

print("#" * 50, 1)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1


In [57]:
print(x[1:])
print(x[1:, 3:])

print("#" * 50, 2)

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2


In [58]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1

print(y)
print(y[1:4, 1:4])

print("#" * 50, 3)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3


In [59]:
z = torch.tensor(
    [[1, 2, 3, 4],
     [2, 3, 4, 5],
     [5, 6, 7, 8]]
)

print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping.py

In [60]:
import torch

In [61]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
t3 = t1.reshape(1, 6)

print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4) # the parameter in arange() should be the multiple of view()'s parameters
t5 = torch.arange(6).view(2, 3)

print(t4)
print(t5)

print("#" * 50, 1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1


In [62]:
t6 = torch.tensor([[[1], [2], [3]]]) # tensor shape = (1, 3, 1)
t7 = t6.squeeze() # remove all dimensions of size 1, tensor shape = (3, )
t8 = t6.squeeze(0) # remove dimension at position 0, tensor shape = (3, 1)
# 압축

print(t7)
print(t8)

print("#" * 50, 2)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2


In [63]:
t9 = torch.tensor([1, 2, 3]) # original shape = (3, )
t10 = t9.unsqueeze(1) # reshaped shape = (3, 1)

print(t9)
print(t10)

t11 = torch.tensor( # origianl shape = (2, 3)
    [[1, 2, 3],
     [4, 5, 6]]
)
t12 = t11.unsqueeze(1) # reshaped shape = (2, 1, 3)

print(t12, t12.shape)

print("#" * 50, 3)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3


In [64]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # origianl shape = (2, 3)
t14 = t13.flatten() # make tensor flat

print(t14)

t15 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
t16 = torch.flatten(t15)
t17 = torch.flatten(t15, start_dim = 1) # make flat from start_dim to end_dim

print(t16)
print(t17)

print("#" * 50, 4)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4


In [65]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size()) # change dimension corresponding index
# index 0 : 2, index 1 : 3, index 2 : 5
# index 2, 0, 1 -> dimension 5, 2, 3

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
t20 = torch.permute(t19, dims=(0, 1)) # becomes (2, 3)
t21 = torch.permute(t19, dims=(1, 0)) # becomes (3, 2)

print(t20)
print(t21)

t22 = torch.transpose(t19, 0, 1)

print(t22)

t23 = torch.t(t19)

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat.py

In [66]:
import torch

In [67]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])
t4 = torch.cat([t1, t2, t3], dim = 1)

print(t4.shape)

print("#" * 50, 1)

torch.Size([2, 6, 3])
################################################## 1


In [68]:
t5 = torch.arange(0, 3)
t6 = torch.arange(3, 8)
t7 = torch.cat((t5, t6), dim = 0)

print(t7.shape)
print(t7)

print("#" * 50, 2)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2


In [69]:
t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)
t10 = torch.cat((t8, t9), dim = 0)

print(t10.size())
print(t10)

t11 = torch.cat((t8, t9), dim = 1)

print(t11.size())
print(t11)

print("#" * 50, 3)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3


In [70]:
t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)
t15 = torch.cat((t12, t13, t14), dim = 0)

print(t15.size())
print(t15)

t16 = torch.cat((t12, t13, t14), dim = 1)
print(t16.size())
print(t16)

print("#" * 50, 4)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4


In [71]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)
t19 = torch.cat((t17, t18), dim = 0)

print(t19.size())
print(t19)

t20 = torch.cat((t17, t18), dim = 1)

print(t20.size())
print(t20)

t21 = torch.cat((t17, t18), dim = 2)

print(t21.size())
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking.py

In [72]:
import torch

In [73]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
t3 = torch.stack([t1, t2], dim = 0) # not only catenate both tensor, but also extend dimension
t4 = torch.cat([t1.unsqueeze(dim = 0), t2.unsqueeze(dim = 0)], dim = 0) # as same as stacking tensor

print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim = 1)
t6 = torch.cat([t1.unsqueeze(dim = 1), t2.unsqueeze(dim = 1)], dim = 1)

print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim = 2)
t8 = torch.cat([t1.unsqueeze(dim = 2), t2.unsqueeze(dim = 2)], dim = 2)

print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1


In [74]:
t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)

print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim = 0)

print(t11.size())
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim = 0)

print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim = 1)

print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim = 1)

print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# n_tensor_vstack_hstack.py

In [75]:
import torch

In [76]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2)) # stack vertically, which means 수직으로, 위아래로

print(t3)

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

print(t6)

t7 = torch.tensor(
    [[[1, 2, 3], [4, 5, 6]],
     [[7, 8, 9], [10, 11, 12]]]
)

print(t7.shape)

t8 = torch.tensor(
    [[[13, 14, 15], [16, 17, 18]],
     [[19, 20, 21], [22, 23, 24]]]
)

print(t8.shape)
print(t8)

t9 = torch.vstack([t7, t8])

print(t9.shape)
print(t9)

print("#" * 50, 1)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1


In [77]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))

print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))

print(t15)

t16 = torch.tensor(
    [[[1, 2, 3], [4, 5, 6]],
     [[7, 8, 9], [10, 11, 12]]]
)

print(t16.shape)

t17 = torch.tensor(
    [[[13, 14, 15], [16, 17, 18]],
     [[19, 20, 21], [22, 23, 24]]]
)

print(t17.shape)

t18 = torch.hstack([t16, t17])

print(t18.shape)
print(t18)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


## 취득한 기술적 사항 / 고찰

- tensor는 numpy와 생김새가 유사하지만, 쓰임새가 다르다.
- tensor의 생성, 초기화, 형태, 차원 등 tensor의 속성들에 대해 학습했다.
- tensor를 다루는 방법을 알게되었다.
    - view를 통해 tensor의 구조를 변경하지 않고, 일부분을 참조할 수 있다.
    - stack을 통해 tensor를 합칠 수 있다. 이때, 차원이 추가된다.
- tensor 곱, 합 등의 연산이 가능하단 것을 알게 되었고, 이때 주의해야 할 제약사항이 있단 것을 알았다.
    - 차원이 서로가 배수관계에 있을 때만 가능하다.
    - 예시로 2, 3 차원은 불가능하다.
    - 2, 4 차원은 가능하다.
    - 위치가 일치하는 요소끼리 연산된다.
    - 따로 행렬 곱처럼 tensor 연산을 해줄 수도 있다.
    - 스칼라값과 연산시 모든 요소에 적용된다.
- squeeze, unsqueeze를 통해 차원을 늘리거나 줄일 수 있다는 것을 알게 되었다.
    - 차원이 늘거나 준다고 해서 요소의 개수가 바뀌진 않는다.
- tensor 생성시 eye라는 함수를 통해 단위 행렬을 만들 수 있단 것을 알았다.
    - 이후 one-hot vector 생성시 굉장히 유용하게 쓰일 것 같다.

## 숙제 후기

- hw1_2.ipynb에 작성하겠습니다.