# learn how to use 'tensor'

In [22]:
import torch
import numpy as np

### Class & function
 - Tensor(input, device)
 - tensor(input, device)
 - dtype
 - device
 - requires_grad
 - size()
 - shape

In [15]:
t1 = torch.Tensor([[1, 2, 3], [1, 2, 3]], device='cpu')

print(t1.dtype)
print(t1.device)
print(t1.requires_grad) # True : maintain gradient
print(t1.size())
print(t1.shape)

torch.float32
cpu
False
torch.Size([2, 3])
torch.Size([2, 3])


In [17]:
t2 = torch.tensor([1, 2, 3], device='cpu')

print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64


In [20]:
t3 = torch.Tensor([[1, 2], [3, 4]])

print(t2.ndim)
print(t3.ndim)

1
2


# initialization tensor

### Class & function
 - Tensor(input)
 - tensor(input)
 - as_tensor(input)

In [30]:
l1 = [1]
t1 = torch.Tensor(l1)   # deep copy

l1[0] = 100

l1 = [1]
t2 = torch.tensor(l1)   # deep copy

l1[0] = 100

l1 = [1]
t3 = torch.as_tensor(l1)    # deep copy

l1[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1.])
tensor([1])
tensor([1])


In [29]:
l2 = np.array([1])
t1 = torch.Tensor(l2)   # deep copy

l2[0] = 100

l2 = np.array([1])
t2 = torch.tensor(l2)   # deep copy

l2[0] = 100

l2 = np.array([1])
t3 = torch.as_tensor(l2)    # shallow copy

l2[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1.])
tensor([1], dtype=torch.int32)
tensor([100], dtype=torch.int32)


## initialization with constant values

### function
 - ones
 - ones_like
 - zeros
 - zeors_like
 - empty
 - empty_like
 - eye

In [34]:
t1 = torch.ones(size=(5,))  # if size=(5), it occurs error
t1_like = torch.zeros_like(input=t1)    # same shape with t1, but init into 0 values

print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])


In [36]:
t = torch.zeros(size=(4,))  # opposite with ones
t_like = torch.ones_like(input=t)   # opposite with zeors_like

print(t)
print(t_like)

tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])


In [37]:
t = torch.eye(n=3)
print(t)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## initialization with random values
 - randint(low, high, size)
 - rand(size)
 - randn(size)
 - normal(mean, std, size)
 - linspace(start, end, steps)
 - arange(start, end, steps) or arange(end)
 - manual_seed(seed)

In [69]:
t = torch.randint(low=10, high=20, size=(1, 2)) # int64 between low and high
print(t)
print(t.dtype)

t = torch.rand(size=(1, 3)) # float32 between 0 and 1
print(t)
print(t.dtype)

t = torch.randn(size=(1, 3))    # float32 between 0 and 1 which is nomalized
print(t)
print(t.dtype)

t = torch.normal(mean=10.0, std=1.0, size=(3, 2))   # float32 which is nomalize with given mean and std
print(t)
print(t.dtype)

t = torch.linspace(start=0.0, end=5.0, steps=3) # give values which are evenly spaced from start to end
print(t)
print(t.dtype)

t = torch.arange(5) # give sequential values
print(t)
print(t.dtype)

tensor([[15, 17]])
torch.int64
tensor([[0.9397, 0.8656, 0.5207]])
torch.float32
tensor([[-0.9610, -0.6572,  0.0337]])
torch.float32
tensor([[10.5095,  8.7066],
        [10.0326,  8.0829],
        [11.1867,  8.9653]])
torch.float32
tensor([0.0000, 2.5000, 5.0000])
torch.float32
tensor([0, 1, 2, 3, 4])
torch.int64


In [75]:
seed = 1729

torch.manual_seed(seed) # give a seed

random = torch.rand(2, 3)
print(random)

random = torch.rand(2, 3)
print(random)

torch.manual_seed(seed) # generate same value tensor

random = torch.rand(2, 3)
print(random)

random = torch.rand(2, 3)
print(random)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


## type conversion
 - float()  == float32() == dtype=torch.float32 == dtype=torch.float
 - double() == float64() == same
 - long()   == int64()   == same
 - int()    == int32()   == same
 - short()  == int16()   == same

In [91]:
t = torch.rand((2, 3), dtype=torch.float64) * 20    # same as numpy
print(t)

t = torch.ones((2, 3))
print(t.dtype)

t = t.to(torch.int64)
print(t.dtype)

t = torch.zeros((10, 2)).double()   # dtype=torch.double == float64 == .double()
print(t.dtype)

t = torch.ones((10, 2)).long()
print(t.dtype)

t = torch.ones((10, 2)).int()
print(t.dtype)

t = torch.ones((10, 2)).float()
print(t.dtype)

t = torch.tensor([[1, 2]], dtype=torch.int64)
print(t.dtype)
print(t)

t_double = torch.zeros((10, 2), dtype=torch.double)
t_short = torch.ones((10, 2), dtype=torch.short)
print((t_double * t_short).dtype)   # fit in larger dtype

tensor([[11.1366, 12.0802,  1.1674],
        [19.2329,  7.3395,  7.3704]], dtype=torch.float64)
torch.float32
torch.int64
torch.float64
torch.int64
torch.int32
torch.float32
torch.int64
tensor([[1, 2]])
torch.float64


## tensor operations
 - add(t1, t2) == t1 + t2
 - sub(t1, t2) == t1 - t2
 - mul(t1, t2) == t1 * t2
 - div(t1, t2) == t1 / t2
 - dot(t1, t2)
 - mm(t1, t2)
 - bmm(t1, t2)
 - matmul(t1, t2)
    - this function have diffrent operation due to input tensor shape

In [97]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)   # same result
print(t4)

t3 = torch.sub(t1, t2)
t4 = t1 - t2
print(t3)   # same result
print(t4)

t3 = torch.mul(t1, t2)
t4 = t1 * t2
print(t3)   # same result
print(t4)

t3 = torch.div(t1, t2)
t4 = t1 / t2
print(t3)   # same result
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [107]:
t = torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))  # return scalar
print(t)
print(t.shape, t1.dtype)   # scalar shape is [](empty)

t1 = torch.randn(2, 3)
t2 = torch.randn(3, 2)
t3 = torch.mm(t1, t2)   # matrix multiplication, 2 by 3 matrix * 3 by 2 matrix = 2 by 2 matrix
print(t3)
print(t3.shape, t3.dtype)

t1 = torch.randn(10, 3, 4)
t2 = torch.randn(10, 4, 5)
# matrix multiplication in each batch, should have same size of first dimension(batch)
# also, second and third dimension require the matrix multiplication conditions
t3 = torch.bmm(t1, t2)  
print(t3)
print(t3.shape, t3.dtype)

tensor(7)
torch.Size([]) torch.float32
tensor([[-2.1556,  1.3355],
        [ 0.0635,  0.2531]])
torch.Size([2, 2]) torch.float32
tensor([[[-1.3138,  1.5804, -1.9574,  1.9792, -2.2693],
         [-0.4199, -0.4170, -0.1332, -0.2363,  0.0924],
         [ 2.1672,  0.2358, -1.8130, -3.1001, -3.6671]],

        [[ 0.3788,  1.8271,  0.5129,  0.1567,  1.3297],
         [-1.4071, -4.7723,  0.0095, -2.7939, -3.8810],
         [-0.7108,  0.9634,  1.9953,  0.4371,  4.7223]],

        [[ 0.6755,  1.6586, -0.6297,  0.1059, -0.1860],
         [-0.9836, -0.1442, -0.5868, -0.1504,  2.3762],
         [-0.6054,  3.1675,  0.0069,  1.8290,  1.5931]],

        [[-0.5758,  0.6423, -0.8076, -0.6445,  0.0181],
         [-1.7860, -1.0630, -0.0417,  1.5427,  0.7346],
         [-0.1557, -0.0988, -0.8932,  0.6251, -0.1279]],

        [[-2.0236, -3.0079, -3.3157, -3.0708, -4.3018],
         [-0.8942, -0.0330, -0.4446, -0.0345,  0.2598],
         [-0.3469,  1.4834,  0.1643,  0.6069,  1.2363]],

        [[ 0.0897,  1

In [118]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([3, 2, 1])
t3 = torch.matmul(t1, t2)   # give dot product for each dimension
print(t3)
print(t3.shape, t3.dtype)

t1 = torch.tensor([
    [1, 2, 3],
    [1, 2, 3]
])
t2 = torch.tensor([1, 2, 3])
t3 = torch.matmul(t1, t2)   # give broadcasted dot product for each dimension
print(t3)
print(t3.shape, t3.dtype)

t1 = torch.randn((10, 3, 4))
t2 = torch.randn((4))
t3 = torch.matmul(t1, t2)   # give broadcasted dot product for each dimension
print(t3)
print(t3.shape, t3.dtype)

t1 = torch.randn((10, 3, 4))
t2 = torch.randn((10, 4, 5))
t3 = torch.matmul(t1, t2)   # bmm
print(t3)
print(t3.shape, t3.dtype)

t1 = torch.randn((10, 3, 4))
t2 = torch.randn((4, 5))
t3 = torch.matmul(t1, t2)   # bmm
print(t3)
print(t3.shape, t3.dtype)

tensor(10)
torch.Size([]) torch.int64
tensor([14, 14])
torch.Size([2]) torch.int64
tensor([[ 1.4777, -1.4428,  2.4095],
        [-5.6580, -0.7669, -2.1990],
        [-2.1852, -0.0415,  1.6347],
        [ 4.7323, -1.6456, -2.7775],
        [ 1.6278,  1.3732, -2.3977],
        [ 0.1312,  0.4262, -4.4359],
        [-1.7556,  2.5503,  0.0162],
        [ 1.7866,  2.3301,  0.5956],
        [ 1.6453,  0.3452, -2.1554],
        [-1.3541, -2.6683, -3.3647]])
torch.Size([10, 3]) torch.float32
tensor([[[-2.2905e+00,  3.1359e-01,  2.3624e+00, -8.2984e-01,  5.2300e+00],
         [ 8.1861e-01, -4.8396e-01,  3.5687e-01, -1.6698e+00, -1.6391e+00],
         [-1.0551e+00, -1.3649e+00,  2.3021e-01,  5.1073e-01, -1.7613e+00]],

        [[ 3.1310e-01,  7.8158e-01,  5.1641e-01,  1.8676e+00, -3.4355e+00],
         [ 9.7856e-01, -5.8450e-01,  1.2196e-01, -2.0199e-01, -1.4100e+00],
         [-8.6291e-01,  2.5384e-01, -4.0761e-01, -2.6518e-01,  2.2431e+00]],

        [[-3.4529e+00,  2.5768e+00, -9.2231e-01, -2.

## tensor broadcasting
### tensor works like numpy array
 - tensor shape(size) goes with the bigger dimension.
 - if the smaller dimesion value is not the measure of the bigger one, then error occur
 - torch.pow(a, b) == a**b

In [121]:
t = torch.tensor([1.0, 2.0, 3.0])
n = 2.0
print(t * n)    # to each tensor

t1 = torch.tensor([[0, 1], [2, 3], [4, 5]])
t2 = torch.tensor([4, 5])
print(t1 - t2)  # to each tensor in dimension 2
print(t1 + n)
print(t1 - n)
print(t1 * n)
print(t1 / n)

tensor([2., 4., 6.])
tensor([[-4, -4],
        [-2, -2],
        [ 0,  0]])
tensor([[2., 3.],
        [4., 5.],
        [6., 7.]])
tensor([[-2., -1.],
        [ 0.,  1.],
        [ 2.,  3.]])
tensor([[ 0.,  2.],
        [ 4.,  6.],
        [ 8., 10.]])
tensor([[0.0000, 0.5000],
        [1.0000, 1.5000],
        [2.0000, 2.5000]])


In [126]:
def normalize(x):
    return x / 255

t = torch.randn(3, 28, 28)
print(t.shape)
print(normalize(t).size())

torch.Size([3, 28, 28])
torch.Size([3, 28, 28])


In [133]:
t1 = torch.tensor([[1, 2], [0, 3]]) # shape : 2, 2
t2 = torch.tensor([[3, 1]])         # shape : 1, 2
t3 = torch.tensor([[5], [2]])       # shape : 2, 1
t4 = torch.tensor([7])              # shape : 1
print(t1 + t2)
print(t1 + t3)
print(t1 + t4)
print(t2 + t3)
print(t2 + t4)
print(t3 + t4)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[ 8,  9],
        [ 7, 10]])
tensor([[8, 6],
        [5, 3]])
tensor([[10,  8]])
tensor([[12],
        [ 9]])


In [142]:
t1 = torch.ones(4, 3, 2)
t2 = t1 * torch.rand(3, 2)
print(t2.shape)

t3 = t1 * torch.rand(3, 1)
print(t3.shape)

t4 = t1 * torch.rand(1, 2)
print(t4.shape)

t1 = torch.ones(5, 1, 4, 1)
t2 = t1 * torch.rand(2, 1, 1)
print(t2.shape)

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 2, 4, 1])


In [147]:
t = torch.ones(4) * 5
print(t)
print(torch.pow(t, 3))

t = torch.arange(1., 5.)
print(torch.pow(t, t))
print(t**t)

tensor([5., 5., 5., 5.])
tensor([125., 125., 125., 125.])
tensor([  1.,   4.,  27., 256.])
tensor([  1.,   4.,  27., 256.])


## tensor index slicing
 - 1:2
 - :-1

In [158]:
t = torch.tensor([  # shape : 3, 5
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
])
print(t[1])
print(t[:, 1])  # just : is need to express second dimesion.
print(t[1, 2])
print(t[:, -1])

print(t[1:])
print(t[1:, 3:])

t = torch.zeros((6, 6))
t[1:4, 2] = 1
print(t)
print(t[1:4, 1:4])

tensor([1, 2, 3, 4, 5])
tensor([2, 2, 2])
tensor(3)
tensor([5, 5, 5])
tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])
tensor([[4, 5],
        [4, 5]])


tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

## tensor reshaping
 - view()
 - reshape()
 - unsqueeze()
 - squeeze()
 - flatten() == torch.flatten()
 - permute() == torch.permute()
 - transpose() == torch.transpose()
 - t() == torch.t() -> 2D transpose

In [185]:
t = torch.ones((2, 3))
print(t.view(3, 2))
print(t.reshape(1, 6))

t = torch.arange(8).view(2, 4)
print(t)

t = torch.ones((1, 3, 1))
print(t.squeeze().shape)    # remove all dimension 1
print(t.squeeze(0).shape)   # remove dimesion at given index
print(t.squeeze(-1).shape)

t = torch.ones(3)
print(t.shape)
print(t.unsqueeze(1).shape) # add dimension at given index
# unsqueeze needs more than one argument

t = torch.ones(2, 3)
print(t.unsqueeze(1).shape) # will be 2, 1, 3

t = torch.ones(3, 4)
print(t.flatten().shape) # will be 12

t = torch.ones(3, 4, 5, 2)
print(t.flatten().shape)    # make tensor into 1 dimesion
print(torch.flatten(t, start_dim=1).shape)  # start flatten after given start_dim

t = torch.ones(1, 2, 3, 4)
print(torch.permute(t, (3, 2, 0, 1)).shape) # change dimension into given sequence of index
print(t.permute((3, 2, 0, 1)).shape)
print(t.transpose(0, 1).shape) # change the dimension of given index

t = torch.ones(1, 2)
print(t.t().shape)  # just used in two dimension

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1., 1., 1., 1., 1.]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
torch.Size([3])
torch.Size([3, 1])
torch.Size([1, 3])
torch.Size([3])
torch.Size([3, 1])
torch.Size([2, 1, 3])
torch.Size([12])
torch.Size([120])
torch.Size([3, 40])
torch.Size([4, 3, 1, 2])
torch.Size([4, 3, 1, 2])
torch.Size([2, 1, 3, 4])
torch.Size([2, 1])


## tensor concat == cat
### cat should have same dimension except the standard dimesion
 - torch.cat((t1, t2, ...), dim=n) == torch.concat((t1, t2, ...), dim=n)

In [207]:
t1 = torch.zeros((2, 1, 3))
t2 = torch.ones((2, 3, 3))
t3 = torch.zeros((2, 2, 3))
print(torch.cat((t1, t2, t3), dim=1).shape)     # should have same dimension except the standard dimension

t1 = torch.arange(0, 3)
t2 = torch.arange(3, 8)
print(torch.cat((t1, t2), dim=0))

t1 = torch.arange(0, 6).reshape((2, 3))
t2 = torch.arange(6, 12).reshape((2, 3))
print(torch.cat((t1, t2), dim=0).shape)

torch.Size([2, 6, 3])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
torch.Size([4, 3])


## tensor stacking
 - tensor.stack((t1, t2), dim=n) = tensor.cat((t1.unsqueeze(dim=n), t2.unsqueeze(dim=n)), dim=n)
 - tensor.hstack((t1, t2)) = tensor.cat((t1, t2), dim=0)
    - if t1, t2 dimension = 1 : tensor.stack((t1, t2), dim=0)
 - tensor.vstack((t1, t2)) = tensor.cat((t1, t2), dim=1)
    - if t1, t2 dimension = 1 : tensor.cat((t1, t2), dim=0)

In [232]:
t1 = torch.ones(2, 3)
t2 = torch.zeros(2, 3)
t3 = torch.stack((t1, t2), dim=0)   # should have same dimension, add additional dimension at the given dimension
print(t3.shape)

t4 = torch.cat((t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)), dim=0)
print(t4.shape)

print(t3.equal(t4)) # stack is same as unsqueeze cat

t1 = torch.arange(0, 3)
t2 = torch.arange(3, 6)
t3 = torch.stack((t1, t2), dim=0)   # stack is not a just a merge, add additional dimension
print(t3)
print(torch.stack((t1, t2), dim=0).equal(torch.cat((t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)), dim=0)))

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
True
tensor([[0, 1, 2],
        [3, 4, 5]])
True


In [252]:
t1 = torch.arange(0, 16).reshape((2, 2, 2, 2))
t2 = torch.arange(16, 32).reshape((2, 2, 2, 2))
print(torch.vstack((t1, t2)).shape)   # vertical stack, stack at the 0 dimension
print(torch.hstack((t1, t2)).shape)   # horizontal stack, stack at the 1 dimension
print(torch.cat((t1, t2), dim=0).shape)
print(torch.cat((t1, t2), dim=1).shape)


t1 = torch.arange(0, 16)
t2 = torch.arange(16, 32)
print(torch.vstack((t1, t2)).shape)   # if given tensors are 1 dimension tensor, add additional tensor at dim=0
print(torch.hstack((t1, t2)).shape)   # if given tensors are 1 dimension tensor, stack at 0 dimension
print(torch.stack((t1, t2), dim=0).shape)
print(torch.cat((t1, t2), dim=0).shape)

torch.Size([4, 2, 2, 2])
torch.Size([2, 4, 2, 2])
torch.Size([4, 2, 2, 2])
torch.Size([2, 4, 2, 2])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
